---
- hosts: test_env
  user: ansible
  become: true
  tasks:
  - name: pull docker image
    command: docker pull insta7120/my-address:v1.0

  - name: stop running container
    command: docker stop test-server

  - name: remove stopped container
    command: docker rm test-server

  - name: run container
    command: docker run -d --name test-server -p 8080:8080 insta7120/my-address:v1.0